# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db_provider:
          entity:
              class: AppBundle:User
              property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: /logout
                target: /

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
    access_control:
        - { path: ^/smartphone/create, roles: ROLE_ADMIN }
        - { path: ^/tv/create, roles: ROLE_ADMIN}
        - { path: ^/laptop/create, roles: ROLE_ADMIN }
        - { path: ^/tablet/create, roles: ROLE_ADMIN}
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/edit, roles: ROLE_ADMIN }
        - { path: ^/delete, roles: ROLE_ADMIN }