<?php

namespace AppBundle\Repository;

/**
 * LaptopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaptopRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllLaptops()
    {
        $sql = "SELECT * FROM products
        WHERE type = :type";
        $params = array(
            'type' => 'laptop',
        );

        return $this->getEntityManager()->getConnection()->executeQuery($sql, $params)->fetchAll();
    }

    public function specificationsForOne($id)
    {
        $sql = "SELECT * FROM products
        INNER JOIN laptops on products.id = laptops.product_id
        WHERE laptops.product_id = :id";
        $params = array(
            'id' => $id,
        );

        return $this->getEntityManager()->getConnection()->executeQuery($sql, $params)->fetchAll();
    }

    public function getAllLaptopsNewToOld()
    {
        $sql = "SELECT * FROM products
        WHERE type = :type
        ORDER BY date_added DESC";
        $params = array(
            'type' => 'laptop',
        );

        return $this->getEntityManager()->getConnection()->executeQuery($sql, $params)->fetchAll();
    }

    public function getAllLaptopsOldToNew()
    {
        $sql = "SELECT * FROM products
        WHERE type = :type
        ORDER BY date_added ASC";
        $params = array(
            'type' => 'laptop',
        );

        return $this->getEntityManager()->getConnection()->executeQuery($sql, $params)->fetchAll();
    }

    public function getAllLaptopsHighToLow()
    {
        $sql = "SELECT * FROM products
        WHERE type = :type
        ORDER BY promotion_price DESC";
        $params = array(
            'type' => 'laptop',
        );

        return $this->getEntityManager()->getConnection()->executeQuery($sql, $params)->fetchAll();
    }

    public function getAllLaptopsLowToHigh()
    {
        $sql = "SELECT * FROM products
        WHERE type = :type
        ORDER BY promotion_price ASC";
        $params = array(
            'type' => 'laptop',
        );

        return $this->getEntityManager()->getConnection()->executeQuery($sql, $params)->fetchAll();
    }

    public function getOnlyDiscount()
    {
        $sql = "SELECT * FROM products
        WHERE type = :type AND discount > 0";
        $params = array(
            'type' => 'laptop',
        );

        return $this->getEntityManager()->getConnection()->executeQuery($sql, $params)->fetchAll();
    }
}
