<?php

namespace AppBundle\Repository;

/**
 * LaptopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaptopRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllLaptops()
    {
        $sql = "SELECT * FROM products
        WHERE type = :type";
        $params = array(
            'type' => 'laptop',
        );

        return $this->getEntityManager()->getConnection()->executeQuery($sql, $params)->fetchAll();
    }

    public function specificationsForOne($id)
    {
        $sql = "SELECT * FROM products
        INNER JOIN laptops on products.id = laptops.product_id
        WHERE laptops.product_id = :id";
        $params = array(
            'id' => $id,
        );

        return $this->getEntityManager()->getConnection()->executeQuery($sql, $params)->fetchAll()[0];
    }
}
