<?php

namespace AppBundle\Repository;

/**
 * ProductInCartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductInCartRepository extends \Doctrine\ORM\EntityRepository
{
}
