<?php

namespace AppBundle\Repository;


/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNewestProds()
    {
        $sql = "SELECT * FROM products
        WHERE quantity > 0
        ORDER BY date_added DESC
        LIMIT 10";

        return $this->getEntityManager()->getConnection()->executeQuery($sql)->fetchAll();
    }

    public function getProdByMakeAndType($make, $type)
    {
        $sql = "SELECT * FROM products
        WHERE type=:type AND UPPER(make) = UPPER(:make)";
        $params = array(
            'type' => $type,
            'make' => $make
        );

        return $this->getEntityManager()->getConnection()->executeQuery($sql, $params)->fetchAll();
    }
}
