<?php

namespace AppBundle\Repository;

/**
 * AdditionalImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdditionalImageRepository extends \Doctrine\ORM\EntityRepository
{
}
