<?php

namespace AppBundle\Repository;

/**
 * AdditionalImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdditionalImageRepository extends \Doctrine\ORM\EntityRepository
{
    public function removeEmptyImages()
    {
        $sql = "DELETE FROM additional_images
        WHERE address = ''";

        return $this->getEntityManager()->getConnection()->executeQuery($sql);
    }
}
