<?php

namespace AppBundle\Repository;

/**
 * CarAdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarAdRepository extends \Doctrine\ORM\EntityRepository
{
}
