<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserSells($username)
    {
        $sql = "SELECT cameras.id, make, model, price, image_url AS imageUrl FROM cameras
        INNER JOIN users on users.id = cameras.user_id
        WHERE username = :username";

        $params = array(
            'username' => $username,
        );

        return $this->getEntityManager()->getConnection()->executeQuery($sql, $params)->fetchAll();
    }

    public function deleteUser($id)
    {
        $sql = "DELETE FROM users
        WHERE id = :id;";

        $params = array(
            'id' => $id,
        );

        $this->getEntityManager()->getConnection()->executeQuery($sql, $params);
    }
}
