<?php

namespace AppBundle\Repository;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends \Doctrine\ORM\EntityRepository
{
    public function filterByMake($make)
    {
        return $this->createQueryBuilder('c')
            ->where('c.make = :make')
            ->setParameter('make', $make)
            ->orderBy('c.make', 'ASC')
            ->addOrderBy('c.travelled_distance', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function getParts($id)
    {
        $sql = 'SELECT parts.id, name, price, cars.id
                FROM parts
                INNER JOIN cars ON cars.id = parts.id
                WHERE cars.id = :id;';
        $params = array(
            'id' => $id,
        );

        return $this->getEntityManager()->getConnection()->executeQuery($sql, $params)->fetchAll();
    }
}
