<?php

namespace AppBundle\Repository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCustomersByGivenOrder($order)
    {
        return $this->createQueryBuilder('customers')
            ->orderBy('customers.birthDate', $order)
            ->addOrderBy('customers.isYoungDriver', 'ASC')
            ->getQuery()
            ->getResult();
    }
}
