<?php

namespace AppBundle\Repository;

/**
 * SupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSuppliersByOrigin(int $isImporter)
    {
        return $this->createQueryBuilder('s')
            ->where('s.isImporter = :isImporter')
            ->setParameter('isImporter', $isImporter)
            ->getQuery()
            ->getResult();
    }
}
