<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function removeEmptyTags()
    {
        $sql = 'DELETE FROM tags WHERE name = ""';

        return $this->getEntityManager()->getConnection()->executeQuery($sql);
    }

    public function removeAllTagsAndComments($id)
    {
        $sql = 'DELETE FROM tags WHERE article_id = :id;
        DELETE FROM comments WHERE article_id = :id';

        $params = array(
            'id' => $id
        );

        return $this->getEntityManager()->getConnection()->executeQuery($sql, $params);
    }

    public function latestArticles()
    {
        $sql = 'SELECT * FROM articles
        ORDER BY date_added DESC
        LIMIT 6';

        return $this->getEntityManager()->getConnection()->executeQuery($sql)->fetchAll();

    }

    public function getArticlesFromHabitat($habitat)
    {
        $sql = "SELECT * FROM articles
        WHERE habitat = :habitat";

        $params = array(
            'habitat' => $habitat
        );

        return $this->getEntityManager()->getConnection()->executeQuery($sql, $params)->fetchAll();
    }

    public function getByTagName($tagName)
    {
        $sql = "SELECT title, slug, image_address, tags.name, articles.id FROM articles
        INNER JOIN tags ON article_id = articles.id
        WHERE tags.name LIKE :tagName";

        $params = array(
            'tagName' => $tagName
        );

        return $this->getEntityManager()->getConnection()->executeQuery($sql, $params)->fetchAll();
    }
}
