<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function removeUserComments($id)
    {
        $sql = 'DELETE FROM
        comments WHERE user_id = :id;';

        $params = array(
            'id' => $id
        );

        return $this->getEntityManager()->getConnection()->executeQuery($sql, $params);
    }
}
