<?php

namespace AppBundle\Repository;

/**
 * CameraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CameraRepository extends \Doctrine\ORM\EntityRepository
{
    public function filterByMake($make)
    {
        $query = $this->createQueryBuilder('c')
            ->where('c.make = :make')
            ->setParameter('make', $make)
            ->getQuery();

        return $query->execute();
    }
}
