<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserSells($username)
    {
        $sql = "SELECT cameras.id, make, model, price, quantity, image_url FROM cameras
        INNER JOIN users on users.id = cameras.user_id
        WHERE username = :username";

        $params = array(
            'username' => $username,
        );

        return $this->getEntityManager()->getConnection()->executeQuery($sql, $params)->fetchAll();
    }
}
